server:
  port: 8081

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/gkpay_payment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

simulator:
  base-url: http://localhost:8082
